// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MilitaryApp.Data;

#nullable disable

namespace MilitaryApp.Data.Migrations
{
    [DbContext(typeof(MilitaryContext))]
    [Migration("20251231121427_modification_addSqlView_Func_v3")]
    partial class modification_addSqlView_Func_v3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MilitaryApp.Domain.Battle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Battles");
                });

            modelBuilder.Entity("MilitaryApp.Domain.Horse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MilitaryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MilitaryId")
                        .IsUnique();

                    b.ToTable("Horses");
                });

            modelBuilder.Entity("MilitaryApp.Domain.King", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KingName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kings");
                });

            modelBuilder.Entity("MilitaryApp.Domain.Military", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("KingId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KingId");

                    b.ToTable("Militaries");
                });

            modelBuilder.Entity("MilitaryApp.Domain.MilitaryBattle", b =>
                {
                    b.Property<int>("MilitaryId")
                        .HasColumnType("int");

                    b.Property<int>("BattleId")
                        .HasColumnType("int");

                    b.HasKey("MilitaryId", "BattleId");

                    b.HasIndex("BattleId");

                    b.ToTable("MilitaryBattle");
                });

            modelBuilder.Entity("MilitaryApp.Domain.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MilitaryId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MilitaryId");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("MilitaryApp.Domain.Horse", b =>
                {
                    b.HasOne("MilitaryApp.Domain.Military", null)
                        .WithOne("Horse")
                        .HasForeignKey("MilitaryApp.Domain.Horse", "MilitaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MilitaryApp.Domain.Military", b =>
                {
                    b.HasOne("MilitaryApp.Domain.King", "King")
                        .WithMany()
                        .HasForeignKey("KingId");

                    b.Navigation("King");
                });

            modelBuilder.Entity("MilitaryApp.Domain.MilitaryBattle", b =>
                {
                    b.HasOne("MilitaryApp.Domain.Battle", "Battle")
                        .WithMany("MilitaryBattles")
                        .HasForeignKey("BattleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MilitaryApp.Domain.Military", "Military")
                        .WithMany("MilitaryBattles")
                        .HasForeignKey("MilitaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Battle");

                    b.Navigation("Military");
                });

            modelBuilder.Entity("MilitaryApp.Domain.Quote", b =>
                {
                    b.HasOne("MilitaryApp.Domain.Military", "Military")
                        .WithMany("Quotes")
                        .HasForeignKey("MilitaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Military");
                });

            modelBuilder.Entity("MilitaryApp.Domain.Battle", b =>
                {
                    b.Navigation("MilitaryBattles");
                });

            modelBuilder.Entity("MilitaryApp.Domain.Military", b =>
                {
                    b.Navigation("Horse")
                        .IsRequired();

                    b.Navigation("MilitaryBattles");

                    b.Navigation("Quotes");
                });
#pragma warning restore 612, 618
        }
    }
}
